# Generated by Django 5.0 on 2023-12-13 00:46

import django.db.models.deletion
import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=products.utils.custom_id, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveSmallIntegerField(choices=[(0, 'Sin descuento'), (5, '%5'), (10, '%10'), (15, '%15'), (20, '%20'), (25, '%25'), (30, '%30'), (35, '%35'), (40, '%40'), (45, '%45'), (50, '%50'), (60, '%60')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=products.utils.custom_id, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('date_payment', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Producto relacionado')),
            ],
        ),
    ]
